# -*- coding: utf-8 -*-
"""#DS5H17_Farisyah Lutfiah Hanis_Data Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12hwHgXw-KXWQJMzgXPmH6LctJGaSSnhV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/Dataset/train_housepricing.csv')
pd.set_option('display.max_columns', 100)
df.head()

df.info()

pd.set_option('display.max_columns', 100)
df.describe()

pd.set_option('display.max_columns', 43)
df.describe(include=object) #khusus tipe data object

"""Missing value"""

df.isnull().sum()

missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])

missing_values = df.isnull().sum()/len(df)*100
print(missing_values[missing_values > 0])

#droping column Alley
df = df.drop(['Alley'], axis=1)
df.head()

#droping column PoolQC
df = df.drop(['PoolQC'], axis=1)
df.head()

#droping column Fence
df = df.drop(['Fence'], axis=1)
df.head()

#droping column MiscFeature
df = df.drop(['MiscFeature'], axis=1)
df.head()

# Imputing missing values LotFrontage
print(df["LotFrontage"].mean())
print(df["LotFrontage"].fillna(df["LotFrontage"].mean().round(0)))

# Imputing missing values MasVnrArea
print(df["MasVnrArea"].median())
print(df["MasVnrArea"].fillna(df["MasVnrArea"].median().round(0)))

df.isnull().sum()







